# serverless.yml

service: aws-lambda-express-sample

provider:
  name: aws
  region: ap-northeast-1

functions:
  api:
    handler: index.handler
    name: serverless-express-function-serverless-api
